site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-3
root_domain: v2.cn.vuejs.org
vue_version: 2.7.14
# START SPONSORS
special:
  - name: appwrite
    url: https://appwrite.io
    img: appwrite.svg
    description: Build Fast. Scale Big. All in One Place.
platinum:
  - name: VueMastery
    url: https://www.vuemastery.com/
    img: vuemastery.png
  - name: VueSchool
    url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
  - name: Vehikl
    url: https://vehikl.com/
    img: vehikl.png
  - name: Passionate People
    url: https://passionatepeople.io/
    img: passionate_people.png
  - name: Storyblok
    url: https://www.storyblok.com
    img: storyblok.png
  - name: Ionic
    url: >-
      https://ionicframework.com/vue?utm_source=partner&utm_medium=referral&utm_campaign=vuesponsorship&utm_content=vuedocs
    img: ionic.png?v2
  - name: CodeDict
    url: https://code-dict.com
    img: codedict.svg
  - name: Chrome Frameworks Fund
    url: https://opencollective.com/2021-frameworks-fund
    img: chrome_frameworks_fund.png
  - name: HeroDevs
    url: https://www.herodevs.com/support/vue
    img: herodevs.png
gold:
  - name: Volta
    url: https://volta.net/?utm_source=vuejs.org&utm_campaign=sponsoring/
    img: volta.svg
  - name: Laravel
    url: https://laravel.com
    img: laravel.png
  - name: Tidelift
    url: https://tidelift.com/subscription/npm/vue
    img: tidelift.png
  - name: Intygrate
    url: https://intygrate.com/
    img: intygrate.png
  - name: Bacancy Technology
    url: https://www.bacancytechnology.com/hire-vuejs-developer
    img: bacancy_technology.png
  - name: Y8
    url: https://www.y8.com/
    img: y8.png
  - name: DevExpress
    url: https://js.devexpress.com/
    img: devexpress.png
  - name: FASTCODING Inc
    url: 'https://fastcoding.jp/javascript/ '
    img: fastcoding_inc.svg
  - name: LINE Corporation
    url: https://linecorp.com
    img: line_corporation.png
  - name: EMQ
    url: https://www.emqx.com
    img: emq.png
  - name: Fenêtre Online Solutions
    url: https://www.fenetre.nl/
    img: fen_tre_online_solutions.svg
  - name: Ant Design Vue
    url: https://antdv.com
    img: ant_design_vue.png
  - name: MQTT X
    url: https://mqttx.app
    img: mqtt_x.png
  - name: Crisp
    url: https://crisp.chat/en/
    img: crisp.png
  - name: Localazy
    url: >-
      https://localazy.com/blog/how-to-localize-vuejs-app-with-vue-i18n-and-localazy?utm_source=vuejs&utm_medium=banner&utm_campaign=sponsorships_vuejs&utm_content=logo
    img: localazy.svg
  - name: LearnVue
    url: https://learnvue.co
    img: learnvue.png
  - name: Casinoburst.com
    url: https://casinoburst.com/casino-utan-licens/
    img: casinoburst_com.png
  - name: spinsify.com/uk
    url: https://www.spinsify.com/uk/new-casinos
    img: spinsify_com_uk.png
  - name: 'Enkrypt: Ethereum and Polkadot Web3 Wallet'
    url: https://www.enkrypt.com
    img: enkrypt__ethereum_and_polkadot_web3_wallet.svg
  - name: uudetkasinot.com
    url: https://www.uudetkasinot.com
    img: uudetkasinot_com.png
  - name: Fathom Analytics
    url: https://usefathom.com/
    img: fathom_analytics.svg
  - name: Goread.io
    url: https://goread.io/buy-instagram-followers
    img: goread_io.png
  - name: Twicsy
    url: https://twicsy.com/buy-instagram-likes
    img: twicsy.png
  - name: Sentry
    url: https://sentry.io/for/vue?utm_source=vuejs.org&utm_medium=paid-community
    img: sentry.png
  - name: Justanotherpanel
    url: https://justanotherpanel.com/
    img: justanotherpanel.png
  - name: Likes.io
    url: https://likes.io/buy-instagram-followers
    img: likes_io.png
  - name: Howsociable
    url: https://howsociable.com/buy-instagram-followers/
    img: howsociable.png
  - name: Poprey.com
    url: https://poprey.com/
    img: poprey_com.png
  - name: Ilmaiset Pitkävetovihjeet
    url: https://www.vedonlyontibonukset.com/pitkavetovihjeet
    img: ilmaiset_pitk_vetovihjeet.png
  - name: Metoree
    url: https://us.metoree.com/
    img: metoree.png
  - name: Famoid
    url: https://famoid.com/
    img: famoid.png
  - name: Certible
    url: https://www.certible.com
    img: certible.svg
  - name: FORTUNE GAMES
    url: https://www.fortunegames.com
    img: fortune_games.png
silver:
  - name: Draxlr
    url: https://www.draxlr.com
    img: draxlr.svg
  - name: Team Extension North America Inc
    url: https://teamextension.io
    img: team_extension_north_america_inc.png
  - name: Free Bets US
    url: https://freebets.us
    img: free_bets_us.png
  - name: Doximity
    url: https://technology.doximity.com/
    img: doximity.png
  - name: Interflora Group
    url: https://www.interflora.fr
    img: interflora_group.png
  - name: Codesmith
    url: https://codesmith.io
    img: codesmith.png
  - name: Optimizers
    url: https://www.optimizers.nl
    img: optimizers.png
  - name: Nettcasino
    url: https://www.nettcasino.com/
    img: nettcasino.png
  - name: Linkbuilding-asia
    url: https://linkbuildingasia.com
    img: linkbuilding_asia.png
  - name: CryptoSEO Agency
    url: https://cryptoseoagency.co
    img: cryptoseo_agency.png
  - name: Linkbuilding Japan
    url: https://linkbuildingjapan.com
    img: linkbuilding_japan.png
  - name: FORTUNE GAMES
    url: https://www.fortunegames.com
    img: fortune_games.png
bronze:
  - name: Derek Pollard
    url: https://polyglotengineer.com/derek.pollard
    img: derek_pollard.png
  - name: BGASoft
    url: https://www.bgasoft.com
    img: bgasoft.png
  - name: RStudio
    url: https://rstudio.com
    img: rstudio.png
  - name: Darkhorse Analytics
    url: https://www.darkhorseanalytics.com/
    img: darkhorse_analytics.png
  - name: vuejs.de - German Vue Community
    url: https://vuejs.de
    img: vuejs_de___german_vue_community.svg
  - name: Liip AG
    url: https://www.liip.ch/en
    img: liip_ag.png
  - name: Bürkert Werke GmbH & Co KG
    url: https://www.burkert.com
    img: b_rkert_werke_gmbh___co_kg.png
  - name: KingBilly
    url: http://kingbilly.com/en-CA
    img: kingbilly.png
# END SPONSORS
video_china:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: youku.png
